language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

script:
 - bash -c 'shopt -s globstar; shellcheck **/*.sh'

git:
  submodules: false

matrix:
  fast_finish: true
